### PR TITLE
Add prototype 'external'

### PR DESCRIPTION
**Pull request by esehara**
I make prototype 'external'. 
I do not know it is right..... What do you think?

Roy:

```
external foobar = 0
```

Translate JS:

```
this.foobar = 0
```

Related : #12

### CODE REVIEW

**Comment by esehara** [comment]
Sorry,I mistake... 
I correct now.

**Comment by paulmillr** [comment]
:-1:, this is very C-ish.

**Comment by esehara** [comment]
Sorry, I mistake "external" .

 I think it means "external" treat Global Valuable example "Document","Window",or etc.
We cannot use "let" for the purpose,because of Error.

```
 ReferenceError: Document is not defined
```

so,Fix "external" can treat undefined valuable in Roy. (not use in REPL now).

```
external document = Document;
```

Trancelate JS:

```
var document = Document;
```

**Comment by alvivi** [comment]
I've been working on this for a while. You can see an early version [here](https://github.com/alvivi/roy/commit/90ccff8e412297ae2815ee039081992c3f69e45d). In my local repository is a bit more advanced, allowing extern function declarations. However, these changes involve type annotations in any expression. For example, this code is valid:

```
extern setTimeout :: Function -> Number -> Unit
// I'm not very happy with this, it should be something like
// extern setTimeout :: (Unit -> Unit) -> Number -> Unit

let x = 4 :: Number
```

It is a major change in the type system, so I think that should be discussed before.

**Comment by puffnfresh** [comment]
Sorry @esehara this wasn't the idea I had in mind, it was more like @alvivi's implementation.

Stuff like this should work already;

```
let r = require
let fs = r "fs"
```

So we can already access external JS. I'm guessing you were getting the `ReferenceError` you got before was because the DOM only defines `document` and not `Document`.

**Comment by esehara** [comment]
Ok,I understand. Thanks :)

**Pull request closed without merging**
