### PR TITLE
document well-typedness of object subtypes

### PR DESCRIPTION
**Pull request by gregwebs**
Please link to the docs - they are sorely needed!

### CODE REVIEW

**Comment by taku0** [comment]
The subtyping of objects seems very restricted.

The following code is typed:

```
let f x = x.y.z

f {x: 1, y: {z:1, zz: 2}}
```

while the following is not:

```
let f x = x.y.z

let g h = h {x: 1, y: {z:1, zz: 2}}

g f
```

The following is also typed.

```
let f x = x.y.z

let g h = h {y: {z:1}}

g f
```

**Comment by taku0** [comment]
Typed X(.

```
let f x = x.y.z

let g h = h {}

g f
```

**Comment by puffnfresh** [comment]
@taku0 that's probably because I haven't implemented structural types using type constraints. Lazy/silly/short-sighted of me.

Fixing that is on my TODO list :)

**Comment by puffnfresh** [comment]
@gregwebs absolutely awesome job. Thanks!

**Pull request merged**
